import styles from '../styles/Home.module.css'
import { createClient } from 'contentful'
import Post from '../components/Post'
import Sidebar from '../components/Sidebar'

export async function getStaticProps () {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID,
    accessToken: process.env.CONTENTFUL_ACCESS_KEY
  })

  const response = await client.getEntries({ content_type: 'post' })

  return {
    props: {
      posts: response.items
    },
    revalidate: 1
  }

}

export default function Posts({ posts }) {
  return (
    <div className="blog-page-wrapper">
      <div className="primary">
        <div className="post-list">
          {posts.map(post => (
            <Post key={post.sys.id} post={post} />
          ))}
        </div>
      </div>
      <div className="secondary">
        <Sidebar items={posts} />
      </div>

      <style jsx>{`
        .blog-page-wrapper {
          border-radius: 3px;
          margin: 0 auto;
          position: relative;
          width: 870px;
        }

        .primary {
          float: right;
          margin: 0 0 0 -282px;
          width: 100%;
        }

        .post-list {
          margin: 0 0 0 282px !important;
        }

        .secondary {
          float: left;
          padding: 71px 30px 30px;
          width: 222px;
          background-color: #030930;
          height: 100%;
        }

      `}</style>
    </div>
  )
}

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.js</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/master/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
